name: aesthetic_clinic
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.2
  connectivity_plus: ^6.1.3
  http: ^1.3.0
  provider: ^6.0.0
  intl: ^0.20.1
  shared_preferences: ^2.5.2
  country_picker: ^2.0.27
  carousel_slider: ^5.1.1
  shimmer: ^3.0.0
  flutter_svg: ^2.0.9
  google_fonts: ^6.2.1


  # ✅ Required for localization
  flutter_localizations:
    sdk: flutter
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica.ttf

  # ✅ Enables code generation for localization
  generate: true
flutter_intl:
  enabled: true
l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
  output-class: AppLocalizations
  synthetic-package: true